export const Patients = [
  {
    name: "John Doe",
    age: 45,
    gender: "Male",
    disease: "Diabetes",
    admittedOn: "2024-01-10",
  },
  {
    name: "Jane Smith",
    age: 34,
    gender: "Female",
    disease: "Hypertension",
    admittedOn: "2024-01-12",
  },
  {
    name: "Mike Johnson",
    age: 29,
    gender: "Male",
    disease: "Asthma",
    admittedOn: "2024-01-15",
  },
  {
    name: "Emily Davis",
    age: 40,
    gender: "Female",
    disease: "COVID-19",
    admittedOn: "2024-01-18",
  },
  {
    name: "David Wilson",
    age: 55,
    gender: "Male",
    disease: "Heart Disease",
    admittedOn: "2024-01-20",
  },
  {
    name: "Emma Brown",
    age: 31,
    gender: "Female",
    disease: "Pneumonia",
    admittedOn: "2024-01-22",
  },
  {
    name: "Chris Miller",
    age: 42,
    gender: "Male",
    disease: "Diabetes",
    admittedOn: "2024-01-25",
  },
  {
    name: "Sophia Anderson",
    age: 38,
    gender: "Female",
    disease: "Hypertension",
    admittedOn: "2024-01-28",
  },
  {
    name: "Daniel Martinez",
    age: 50,
    gender: "Male",
    disease: "Stroke",
    admittedOn: "2024-02-01",
  },
  {
    name: "Olivia Taylor",
    age: 27,
    gender: "Female",
    disease: "Migraine",
    admittedOn: "2024-02-05",
  },
  {
    name: "James White",
    age: 37,
    gender: "Male",
    disease: "Cancer",
    admittedOn: "2024-02-08",
  },
  {
    name: "Ava Thomas",
    age: 29,
    gender: "Female",
    disease: "Asthma",
    admittedOn: "2024-02-12",
  },
  {
    name: "Ethan Harris",
    age: 46,
    gender: "Male",
    disease: "Diabetes",
    admittedOn: "2024-02-15",
  },
  {
    name: "Isabella Clark",
    age: 33,
    gender: "Female",
    disease: "Allergy",
    admittedOn: "2024-02-18",
  },
  {
    name: "William Lewis",
    age: 52,
    gender: "Male",
    disease: "Kidney Disease",
    admittedOn: "2024-02-20",
  },
  {
    name: "Mia Walker",
    age: 36,
    gender: "Female",
    disease: "Thyroid Disorder",
    admittedOn: "2024-02-23",
  },
  {
    name: "Benjamin Hall",
    age: 44,
    gender: "Male",
    disease: "Obesity",
    admittedOn: "2024-02-26",
  },
  {
    name: "Charlotte Allen",
    age: 30,
    gender: "Female",
    disease: "Arthritis",
    admittedOn: "2024-03-01",
  },
  {
    name: "Liam Young",
    age: 48,
    gender: "Male",
    disease: "COPD",
    admittedOn: "2024-03-05",
  },
  {
    name: "Amelia King",
    age: 41,
    gender: "Female",
    disease: "Liver Disease",
    admittedOn: "2024-03-08",
  },
];
